######
##
## The Perl code is generated by atscc2pl
## The starting compilation time is: 2017-10-23: 14h:29m
##
######
sub
_ats2plpre_ML_array0_patsfun_8__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_ML_array0_patsfun_8($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_ML_array0_patsfun_11__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_ML_array0_patsfun_11($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_ML_array0_patsfun_17__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_ML_array0_patsfun_17($cenv->[1], $arg0); }, $env0];
}


sub
ats2plpre_ML_array0_make_elt($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret0;
##
  __patsflab_array0_make_elt:
  $tmpret0 = ats2plpre_arrszref_make_elt($arg0, $arg1);
  return $tmpret0;
} #end-of-function


sub
ats2plpre_ML_array0_size($)
{
##
  my($arg0) = @_;
##
  my $tmpret1;
##
  __patsflab_array0_size:
  $tmpret1 = ats2plpre_arrszref_size($arg0);
  return $tmpret1;
} #end-of-function


sub
ats2plpre_ML_array0_length($)
{
##
  my($arg0) = @_;
##
  my $tmpret2;
##
  __patsflab_array0_length:
  $tmpret2 = ats2plpre_arrszref_size($arg0);
  return $tmpret2;
} #end-of-function


sub
ats2plpre_ML_array0_get_at($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret3;
##
  __patsflab_array0_get_at:
  $tmpret3 = ats2plpre_arrszref_get_at($arg0, $arg1);
  return $tmpret3;
} #end-of-function


sub
ats2plpre_ML_array0_set_at($$$)
{
##
  my($arg0, $arg1, $arg2) = @_;
##
##
  __patsflab_array0_set_at:
  ats2plpre_arrszref_set_at($arg0, $arg1, $arg2);
  return;#_void
} #end-of-function


sub
ats2plpre_ML_array0_exch_at($$$)
{
##
  my($arg0, $arg1, $arg2) = @_;
##
  my $tmpret5;
##
  __patsflab_array0_exch_at:
  $tmpret5 = ats2plpre_arrszref_exch_at($arg0, $arg1, $arg2);
  return $tmpret5;
} #end-of-function


sub
ats2plpre_ML_array0_exists($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret6;
##
  __patsflab_array0_exists:
  $tmpret6 = ats2plpre_arrszref_exists_cloref($arg0, $arg1);
  return $tmpret6;
} #end-of-function


sub
ats2plpre_ML_array0_exists_method($)
{
##
  my($arg0) = @_;
##
  my $tmpret7;
##
  __patsflab_array0_exists_method:
  $tmpret7 = _ats2plpre_ML_array0_patsfun_8__closurerize($arg0);
  return $tmpret7;
} #end-of-function


sub
_ats2plpre_ML_array0_patsfun_8($$)
{
##
  my($env0, $arg0) = @_;
##
  my $tmpret8;
##
  __patsflab__ats2plpre_ML_array0_patsfun_8:
  $tmpret8 = ats2plpre_ML_array0_exists($env0, $arg0);
  return $tmpret8;
} #end-of-function


sub
ats2plpre_ML_array0_forall($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret9;
##
  __patsflab_array0_forall:
  $tmpret9 = ats2plpre_arrszref_forall_cloref($arg0, $arg1);
  return $tmpret9;
} #end-of-function


sub
ats2plpre_ML_array0_forall_method($)
{
##
  my($arg0) = @_;
##
  my $tmpret10;
##
  __patsflab_array0_forall_method:
  $tmpret10 = _ats2plpre_ML_array0_patsfun_11__closurerize($arg0);
  return $tmpret10;
} #end-of-function


sub
_ats2plpre_ML_array0_patsfun_11($$)
{
##
  my($env0, $arg0) = @_;
##
  my $tmpret11;
##
  __patsflab__ats2plpre_ML_array0_patsfun_11:
  $tmpret11 = ats2plpre_ML_array0_forall($env0, $arg0);
  return $tmpret11;
} #end-of-function


sub
array0_find_index($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret12;
  my $tmp17;
##
  __patsflab_array0_find_index:
  $tmp17 = ats2plpre_ML_array0_size($arg0);
  $tmpret12 = _ats2plpre_ML_array0_loop_13($arg1, 0, $tmp17);
  return $tmpret12;
} #end-of-function


sub
_ats2plpre_ML_array0_loop_13($$$)
{
##
  my($env0, $arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret13;
  my $tmp14;
  my $tmp15;
  my $tmp16;
##
  __patsflab__ats2plpre_ML_array0_loop_13:
  $tmp14 = ats2plpre_lt_int0_int0($arg0, $arg1);
  if($tmp14) {
    $tmp15 = &{$env0->[0]}($env0, $arg0);
    if($tmp15) {
      $tmpret13 = $arg0;
    } else {
      $tmp16 = ats2plpre_add_int1_int1($arg0, 1);
      #ATStailcalseq_beg
      $apy0 = $tmp16;
      $apy1 = $arg1;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab__ats2plpre_ML_array0_loop_13;
      #ATStailcalseq_end
    } #endif
  } else {
    $tmpret13 = ats2plpre_neg_int1(1);
  } #endif
  return $tmpret13;
} #end-of-function


sub
ats2plpre_ML_array0_app($$)
{
##
  my($arg0, $arg1) = @_;
##
##
  __patsflab_array0_app:
  ats2plpre_ML_array0_foreach($arg0, $arg1);
  return;#_void
} #end-of-function


sub
ats2plpre_ML_array0_foreach($$)
{
##
  my($arg0, $arg1) = @_;
##
##
  __patsflab_array0_foreach:
  ats2plpre_arrszref_foreach_cloref($arg0, $arg1);
  return;#_void
} #end-of-function


sub
ats2plpre_ML_array0_foreach_method($)
{
##
  my($arg0) = @_;
##
  my $tmpret20;
##
  __patsflab_array0_foreach_method:
  $tmpret20 = _ats2plpre_ML_array0_patsfun_17__closurerize($arg0);
  return $tmpret20;
} #end-of-function


sub
_ats2plpre_ML_array0_patsfun_17($$)
{
##
  my($env0, $arg0) = @_;
##
##
  __patsflab__ats2plpre_ML_array0_patsfun_17:
  ats2plpre_ML_array0_foreach($env0, $arg0);
  return;#_void
} #end-of-function

######
##
## end-of-compilation-unit
##
######
