/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2017-11-12:  9h:13m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */

#include "pats_lintprgm_myint.cats"

/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef struct {
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_1 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_vt_nil_1) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_assert_errmsg) (ats_bool_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_newline) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_string_append) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_neg_bool) (ats_bool_type) ;
ATSextern_fun(ats_int_type, atspre_neg_int) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_sub_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_mul_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_div_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_mod_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_gcd_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_compare_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_int) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_ineg) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ieq) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ineq) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_intinf_2esats__intinf_get_int) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__myintvec0_free) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__indexset_is_member) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_make) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_free) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_choose) (ats_ref_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__myintvecout_addback_prfck () ;
extern
ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__myintvecout0_addback_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
int _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__sasp__indexlst = 0 ;
int _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__sasp__indexset = 0 ;

/* sum constructor declarations */
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVLSTnil_0) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVLSTcons_1) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVLSTmark_2) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVEQLSTnil_0) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVEQLSTcons_1) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVEQLSTmark_2) ;

/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
intknd myint_make_int_02120_intknd (ats_int_type arg0) ;
static
intknd myint_make_intinf_02121_intknd (ats_ptr_type arg0) ;
static
ats_void_type myint_free_02122_intknd (intknd arg0) ;
static
intknd myint_copy_02123_intknd (intknd arg0) ;
static
intknd neg_myint_02124_intknd (intknd arg0) ;
static
intknd neg1_myint_02125_intknd (intknd arg0) ;
static
intknd add_myint_int_02126_intknd (intknd arg0, ats_int_type arg1) ;
static
intknd add01_myint_myint_02127_intknd (intknd arg0, intknd arg1) ;
static
intknd sub01_myint_myint_02128_intknd (intknd arg0, intknd arg1) ;
static
intknd mul01_myint_myint_02129_intknd (intknd arg0, intknd arg1) ;
static
intknd mul10_myint_myint_02130_intknd (intknd arg0, intknd arg1) ;
static
intknd mul11_myint_myint_02131_intknd (intknd arg0, intknd arg1) ;
static
intknd div01_myint_myint_02132_intknd (intknd arg0, intknd arg1) ;
static
intknd div11_myint_myint_02133_intknd (intknd arg0, intknd arg1) ;
static
intknd ediv01_myint_myint_02134_intknd (intknd arg0, intknd arg1) ;
static
intknd mod01_myint_myint_02135_intknd (intknd arg0, intknd arg1) ;
static
intknd mod11_myint_myint_02136_intknd (intknd arg0, intknd arg1) ;
static
intknd gcd01_myint_myint_02137_intknd (intknd arg0, intknd arg1) ;
static
ats_bool_type lt_myint_int_02138_intknd (intknd arg0, ats_int_type arg1) ;
static
ats_bool_type lte_myint_int_02139_intknd (intknd arg0, ats_int_type arg1) ;
static
ats_bool_type gt_myint_int_02140_intknd (intknd arg0, ats_int_type arg1) ;
static
ats_bool_type gte_myint_int_02141_intknd (intknd arg0, ats_int_type arg1) ;
static
ats_bool_type eq_myint_int_02142_intknd (intknd arg0, ats_int_type arg1) ;
static
ats_bool_type neq_myint_int_02143_intknd (intknd arg0, ats_int_type arg1) ;
static
ats_int_type compare_myint_int_02144_intknd (intknd arg0, ats_int_type arg1) ;
static
ats_bool_type lt_myint_myint_02145_intknd (intknd arg0, intknd arg1) ;
static
ats_bool_type lte_myint_myint_02146_intknd (intknd arg0, intknd arg1) ;
static
ats_bool_type gt_myint_myint_02147_intknd (intknd arg0, intknd arg1) ;
static
ats_bool_type gte_myint_myint_02148_intknd (intknd arg0, intknd arg1) ;
static
ats_void_type fprint_myint_02117_intknd (ats_ptr_type arg0, intknd arg1) ;
static
ats_void_type myintvec_free_02164_intknd (ats_ptr_type arg0, ats_int_type arg1) ;
static
ats_int_type cmp_31 (ats_int_type arg0, ats_int_type arg1) ;
static
ats_clo_ptr_type cmp_31_closure_make () ;
static
ats_int_type cmp_31_clofun (ats_clo_ptr_type cloptr, ats_int_type arg0, ats_int_type arg1) ;
static
ats_ptr_type funset_make_nil_02268_ () ;
static
ats_int_type compare_elt_elt_02267_ats_int_type (ats_int_type arg0, ats_int_type arg1, ats_clo_ref_type arg2) ;
static
ats_bool_type aux_36 (ats_int_type env0, ats_clo_ref_type env1, ats_ptr_type arg0) ;
static
ats_clo_ptr_type aux_36_closure_make (ats_int_type env0, ats_clo_ref_type env1) ;
static
ats_bool_type aux_36_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_bool_type funset_is_member_02272_ats_int_type (ats_ptr_type arg0, ats_int_type arg1, ats_clo_ref_type arg2) ;
static
ats_ptr_type ins_40 (ats_int_type env0, ats_clo_ref_type env1, ats_ptr_type arg0, ats_ref_type arg1) ;
static
ats_clo_ptr_type ins_40_closure_make (ats_int_type env0, ats_clo_ref_type env1) ;
static
ats_ptr_type ins_40_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0, ats_ref_type arg1) ;
static
ats_bool_type funset_insert_02274_ats_int_type (ats_ref_type arg0, ats_int_type arg1, ats_clo_ref_type arg2) ;
static
ats_void_type loop_44 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type list_vt_append_01504_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type loop_42 (ats_ptr_type env0, ats_int_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_clo_ptr_type loop_42_closure_make (ats_ptr_type env0) ;
static
ats_ptr_type loop_42_clofun (ats_clo_ptr_type cloptr, ats_int_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_void_type loop_47 (ats_ptr_type arg0) ;
static
ats_void_type list_vt_free_01499_ats_int_type (ats_ptr_type arg0) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 2166(line=78, offs=24) -- 2184(line=78, offs=42)
*/
ATSstaticdec()
intknd
myint_make_int_02120_intknd (ats_int_type arg0) {
/* local vardec */
ATSlocal (intknd, tmp0) ;

__ats_lab_myint_make_int_02120_intknd:
tmp0 = ats_castfn_mac(intknd, arg0) ;
return (tmp0) ;
} /* end of [myint_make_int_02120_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 2223(line=81, offs=27) -- 2290(line=83, offs=4)
*/
ATSstaticdec()
intknd
myint_make_intinf_02121_intknd (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (intknd, tmp1) ;
ATSlocal (ats_int_type, tmp2) ;

__ats_lab_myint_make_intinf_02121_intknd:
tmp2 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_intinf_2esats__intinf_get_int (arg0) ;
tmp1 = ats_castfn_mac(intknd, tmp2) ;
return (tmp1) ;
} /* end of [myint_make_intinf_02121_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 2377(line=88, offs=20) -- 2437(line=90, offs=4)
*/
ATSstaticdec()
ats_void_type
myint_free_02122_intknd (intknd arg0) {
/* local vardec */
// ATSlocal_void (tmp3) ;

__ats_lab_myint_free_02122_intknd:
return /* (tmp3) */ ;
} /* end of [myint_free_02122_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 2491(line=92, offs=30) -- 2514(line=92, offs=53)
*/
ATSstaticdec()
intknd
myint_copy_02123_intknd (intknd arg0) {
/* local vardec */
ATSlocal (intknd, tmp4) ;

__ats_lab_myint_copy_02123_intknd:
tmp4 = ats_castfn_mac(intknd, arg0) ;
return (tmp4) ;
} /* end of [myint_copy_02123_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 2566(line=97, offs=19) -- 2586(line=97, offs=39)
*/
ATSstaticdec()
intknd
neg_myint_02124_intknd (intknd arg0) {
/* local vardec */
ATSlocal (intknd, tmp5) ;
ATSlocal (ats_int_type, tmp6) ;

__ats_lab_neg_myint_02124_intknd:
tmp6 = atspre_neg_int (ats_castfn_mac(ats_int_type, arg0)) ;
tmp5 = ats_castfn_mac(intknd, tmp6) ;
return (tmp5) ;
} /* end of [neg_myint_02124_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 2617(line=99, offs=20) -- 2637(line=99, offs=40)
*/
ATSstaticdec()
intknd
neg1_myint_02125_intknd (intknd arg0) {
/* local vardec */
ATSlocal (intknd, tmp7) ;
ATSlocal (ats_int_type, tmp8) ;

__ats_lab_neg1_myint_02125_intknd:
tmp8 = atspre_neg_int (ats_castfn_mac(ats_int_type, arg0)) ;
tmp7 = ats_castfn_mac(intknd, tmp8) ;
return (tmp7) ;
} /* end of [neg1_myint_02125_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 2693(line=104, offs=23) -- 2719(line=104, offs=49)
*/
ATSstaticdec()
intknd
add_myint_int_02126_intknd (intknd arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (intknd, tmp9) ;
ATSlocal (ats_int_type, tmp10) ;

__ats_lab_add_myint_int_02126_intknd:
tmp10 = atspre_add_int_int (ats_castfn_mac(ats_int_type, arg0), arg1) ;
tmp9 = ats_castfn_mac(intknd, tmp10) ;
return (tmp9) ;
} /* end of [add_myint_int_02126_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 2781(line=110, offs=3) -- 2841(line=112, offs=2)
*/
ATSstaticdec()
intknd
add01_myint_myint_02127_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (intknd, tmp11) ;
ATSlocal (ats_int_type, tmp12) ;

__ats_lab_add01_myint_myint_02127_intknd:
tmp12 = atspre_add_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
tmp11 = ats_castfn_mac(intknd, tmp12) ;
return (tmp11) ;
} /* end of [add01_myint_myint_02127_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 2917(line=116, offs=3) -- 2977(line=118, offs=2)
*/
ATSstaticdec()
intknd
sub01_myint_myint_02128_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (intknd, tmp13) ;
ATSlocal (ats_int_type, tmp14) ;

__ats_lab_sub01_myint_myint_02128_intknd:
tmp14 = atspre_sub_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
tmp13 = ats_castfn_mac(intknd, tmp14) ;
return (tmp13) ;
} /* end of [sub01_myint_myint_02128_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 3072(line=123, offs=27) -- 3105(line=123, offs=60)
*/
ATSstaticdec()
intknd
mul01_myint_myint_02129_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (intknd, tmp15) ;
ATSlocal (ats_int_type, tmp16) ;

__ats_lab_mul01_myint_myint_02129_intknd:
tmp16 = atspre_mul_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
tmp15 = ats_castfn_mac(intknd, tmp16) ;
return (tmp15) ;
} /* end of [mul01_myint_myint_02129_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 3143(line=125, offs=27) -- 3176(line=125, offs=60)
*/
ATSstaticdec()
intknd
mul10_myint_myint_02130_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (intknd, tmp17) ;
ATSlocal (ats_int_type, tmp18) ;

__ats_lab_mul10_myint_myint_02130_intknd:
tmp18 = atspre_mul_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
tmp17 = ats_castfn_mac(intknd, tmp18) ;
return (tmp17) ;
} /* end of [mul10_myint_myint_02130_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 3214(line=127, offs=27) -- 3247(line=127, offs=60)
*/
ATSstaticdec()
intknd
mul11_myint_myint_02131_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (intknd, tmp19) ;
ATSlocal (ats_int_type, tmp20) ;

__ats_lab_mul11_myint_myint_02131_intknd:
tmp20 = atspre_mul_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
tmp19 = ats_castfn_mac(intknd, tmp20) ;
return (tmp19) ;
} /* end of [mul11_myint_myint_02131_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 3309(line=133, offs=3) -- 3369(line=135, offs=2)
*/
ATSstaticdec()
intknd
div01_myint_myint_02132_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (intknd, tmp21) ;
ATSlocal (ats_int_type, tmp22) ;

__ats_lab_div01_myint_myint_02132_intknd:
tmp22 = atspre_div_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
tmp21 = ats_castfn_mac(intknd, tmp22) ;
return (tmp21) ;
} /* end of [div01_myint_myint_02132_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 3445(line=138, offs=27) -- 3478(line=138, offs=60)
*/
ATSstaticdec()
intknd
div11_myint_myint_02133_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (intknd, tmp23) ;
ATSlocal (ats_int_type, tmp24) ;

__ats_lab_div11_myint_myint_02133_intknd:
tmp24 = atspre_div_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
tmp23 = ats_castfn_mac(intknd, tmp24) ;
return (tmp23) ;
} /* end of [div11_myint_myint_02133_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 3520(line=142, offs=3) -- 3580(line=144, offs=2)
*/
ATSstaticdec()
intknd
ediv01_myint_myint_02134_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (intknd, tmp25) ;
ATSlocal (ats_int_type, tmp26) ;

__ats_lab_ediv01_myint_myint_02134_intknd:
tmp26 = atspre_div_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
tmp25 = ats_castfn_mac(intknd, tmp26) ;
return (tmp25) ;
} /* end of [ediv01_myint_myint_02134_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 3678(line=150, offs=3) -- 3746(line=152, offs=2)
*/
ATSstaticdec()
intknd
mod01_myint_myint_02135_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (intknd, tmp27) ;
ATSlocal (ats_int_type, tmp28) ;

__ats_lab_mod01_myint_myint_02135_intknd:
tmp28 = atspre_mod_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
tmp27 = ats_castfn_mac(intknd, tmp28) ;
return (tmp27) ;
} /* end of [mod01_myint_myint_02135_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 3822(line=155, offs=27) -- 3857(line=155, offs=62)
*/
ATSstaticdec()
intknd
mod11_myint_myint_02136_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (intknd, tmp29) ;
ATSlocal (ats_int_type, tmp30) ;

__ats_lab_mod11_myint_myint_02136_intknd:
tmp30 = atspre_mod_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
tmp29 = ats_castfn_mac(intknd, tmp30) ;
return (tmp29) ;
} /* end of [mod11_myint_myint_02136_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 3919(line=161, offs=3) -- 3987(line=163, offs=2)
*/
ATSstaticdec()
intknd
gcd01_myint_myint_02137_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (intknd, tmp31) ;
ATSlocal (ats_int_type, tmp32) ;

__ats_lab_gcd01_myint_myint_02137_intknd:
tmp32 = atspre_gcd_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
tmp31 = ats_castfn_mac(intknd, tmp32) ;
return (tmp31) ;
} /* end of [gcd01_myint_myint_02137_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4077(line=167, offs=32) -- 4098(line=167, offs=53)
*/
ATSstaticdec()
ats_bool_type
lt_myint_int_02138_intknd (intknd arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp33) ;

__ats_lab_lt_myint_int_02138_intknd:
tmp33 = atspre_lt_int_int (ats_castfn_mac(ats_int_type, arg0), arg1) ;
return (tmp33) ;
} /* end of [lt_myint_int_02138_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4131(line=168, offs=33) -- 4153(line=168, offs=55)
*/
ATSstaticdec()
ats_bool_type
lte_myint_int_02139_intknd (intknd arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp34) ;

__ats_lab_lte_myint_int_02139_intknd:
tmp34 = atspre_lte_int_int (ats_castfn_mac(ats_int_type, arg0), arg1) ;
return (tmp34) ;
} /* end of [lte_myint_int_02139_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4185(line=169, offs=32) -- 4206(line=169, offs=53)
*/
ATSstaticdec()
ats_bool_type
gt_myint_int_02140_intknd (intknd arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp35) ;

__ats_lab_gt_myint_int_02140_intknd:
tmp35 = atspre_gt_int_int (ats_castfn_mac(ats_int_type, arg0), arg1) ;
return (tmp35) ;
} /* end of [gt_myint_int_02140_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4239(line=170, offs=33) -- 4261(line=170, offs=55)
*/
ATSstaticdec()
ats_bool_type
gte_myint_int_02141_intknd (intknd arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp36) ;

__ats_lab_gte_myint_int_02141_intknd:
tmp36 = atspre_gte_int_int (ats_castfn_mac(ats_int_type, arg0), arg1) ;
return (tmp36) ;
} /* end of [gte_myint_int_02141_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4293(line=171, offs=32) -- 4314(line=171, offs=53)
*/
ATSstaticdec()
ats_bool_type
eq_myint_int_02142_intknd (intknd arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp37) ;

__ats_lab_eq_myint_int_02142_intknd:
tmp37 = atspre_eq_int_int (ats_castfn_mac(ats_int_type, arg0), arg1) ;
return (tmp37) ;
} /* end of [eq_myint_int_02142_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4347(line=172, offs=33) -- 4369(line=172, offs=55)
*/
ATSstaticdec()
ats_bool_type
neq_myint_int_02143_intknd (intknd arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp38) ;

__ats_lab_neq_myint_int_02143_intknd:
tmp38 = atspre_neq_int_int (ats_castfn_mac(ats_int_type, arg0), arg1) ;
return (tmp38) ;
} /* end of [neq_myint_int_02143_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4406(line=174, offs=27) -- 4436(line=174, offs=57)
*/
ATSstaticdec()
ats_int_type
compare_myint_int_02144_intknd (intknd arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp39) ;

__ats_lab_compare_myint_int_02144_intknd:
tmp39 = atspre_compare_int_int (ats_castfn_mac(ats_int_type, arg0), arg1) ;
return (tmp39) ;
} /* end of [compare_myint_int_02144_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4492(line=178, offs=34) -- 4521(line=178, offs=63)
*/
ATSstaticdec()
ats_bool_type
lt_myint_myint_02145_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp40) ;

__ats_lab_lt_myint_myint_02145_intknd:
tmp40 = atspre_lt_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
return (tmp40) ;
} /* end of [lt_myint_myint_02145_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4557(line=179, offs=35) -- 4587(line=179, offs=65)
*/
ATSstaticdec()
ats_bool_type
lte_myint_myint_02146_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp41) ;

__ats_lab_lte_myint_myint_02146_intknd:
tmp41 = atspre_lte_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
return (tmp41) ;
} /* end of [lte_myint_myint_02146_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4622(line=180, offs=34) -- 4651(line=180, offs=63)
*/
ATSstaticdec()
ats_bool_type
gt_myint_myint_02147_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp42) ;

__ats_lab_gt_myint_myint_02147_intknd:
tmp42 = atspre_gt_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
return (tmp42) ;
} /* end of [gt_myint_myint_02147_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4687(line=181, offs=35) -- 4717(line=181, offs=65)
*/
ATSstaticdec()
ats_bool_type
gte_myint_myint_02148_intknd (intknd arg0, intknd arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp43) ;

__ats_lab_gte_myint_myint_02148_intknd:
tmp43 = atspre_gte_int_int (ats_castfn_mac(ats_int_type, arg0), ats_castfn_mac(ats_int_type, arg1)) ;
return (tmp43) ;
} /* end of [gte_myint_myint_02148_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4772(line=186, offs=22) -- 4809(line=186, offs=59)
*/
ATSstaticdec()
ats_void_type
fprint_myint_02117_intknd (ats_ptr_type arg0, intknd arg1) {
/* local vardec */
// ATSlocal_void (tmp44) ;

__ats_lab_fprint_myint_02117_intknd:
/* tmp44 = */ atspre_fprint_int (arg0, ats_castfn_mac(ats_int_type, arg1)) ;
return /* (tmp44) */ ;
} /* end of [fprint_myint_02117_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_myint_int.dats: 4870(line=192, offs=7) -- 5181(line=204, offs=4)
*/
ATSstaticdec()
ats_void_type
myintvec_free_02164_intknd (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
// ATSlocal_void (tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;

__ats_lab_myintvec_free_02164_intknd:
tmp46 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_2) ;
/* tmp45 = */ atspre_array_ptr_free (tmp46) ;
return /* (tmp45) */ ;
} /* end of [myintvec_free_02164_intknd] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_solve.dats: 8121(line=359, offs=4) -- 8188(line=361, offs=43)
*/
ATSstaticdec()
ats_int_type
cmp_31 (ats_int_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp47) ;

__ats_lab_cmp_31:
tmp47 = atspre_compare_int_int (arg0, arg1) ;
return (tmp47) ;
} /* end of [cmp_31] */

typedef struct {
ats_fun_ptr_type closure_fun ;
} cmp_31_closure_type ;

ats_int_type
cmp_31_clofun (ats_clo_ptr_type cloptr, ats_int_type arg0, ats_int_type arg1) {
return cmp_31 (arg0, arg1) ;
} /* end of function */

ATSinline()
ats_void_type
cmp_31_closure_init (cmp_31_closure_type *p_clo) {
p_clo->closure_fun = (ats_fun_ptr_type)&cmp_31_clofun ;
return ;
} /* end of function */

ats_clo_ptr_type
cmp_31_closure_make () {
cmp_31_closure_type *p_clo = ATS_MALLOC(sizeof(cmp_31_closure_type)) ;
cmp_31_closure_init (p_clo) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/Research/ATS-Anairiats/libats/DATS/funset_listord.dats: 2201(line=74, offs=17) -- 2217(line=74, offs=33)
*/
ATSstaticdec()
ats_ptr_type
funset_make_nil_02268_ () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp49) ;

__ats_lab_funset_make_nil_02268_:
tmp49 = (ats_sum_ptr_type)0 ;
return (tmp49) ;
} /* end of [funset_make_nil_02268_] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_solve.dats: 8326(line=369, offs=13) -- 8353(line=369, offs=40)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__indexset_nil () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp48) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__indexset_nil:
tmp48 = funset_make_nil_02268_ () ;
return (tmp48) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__indexset_nil] */

/*
// /home/hwxi/Research/ATS-Anairiats/libats/DATS/funset_listord.dats: 1887(line=58, offs=32) -- 1915(line=58, offs=60)
*/
ATSstaticdec()
ats_int_type
compare_elt_elt_02267_ats_int_type (ats_int_type arg0, ats_int_type arg1, ats_clo_ref_type arg2) {
/* local vardec */
ATSlocal (ats_int_type, tmp56) ;

__ats_lab_compare_elt_elt_02267_ats_int_type:
tmp56 = ((ats_int_type(*)(ats_clo_ptr_type, ats_int_type, ats_int_type))(ats_closure_fun(arg2))) (arg2, arg0, arg1) ;
return (tmp56) ;
} /* end of [compare_elt_elt_02267_ats_int_type] */

/*
// /home/hwxi/Research/ATS-Anairiats/libats/DATS/funset_listord.dats: 3671(line=138, offs=7) -- 3950(line=144, offs=27)
*/
ATSstaticdec()
ats_bool_type
aux_36 (ats_int_type env0, ats_clo_ref_type env1, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp52) ;
ATSlocal (ats_int_type, tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;
ATSlocal (ats_int_type, tmp55) ;
ATSlocal (ats_bool_type, tmp57) ;
ATSlocal (ats_bool_type, tmp58) ;

__ats_lab_aux_36:
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp53 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp54 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
tmp55 = compare_elt_elt_02267_ats_int_type (env0, tmp53, env1) ;
tmp57 = atspre_gt_int_int (tmp55, 0) ;
if (tmp57) {
tmp52 = ats_false_bool ;
} else {
tmp58 = atspre_lt_int_int (tmp55, 0) ;
if (tmp58) {
arg0 = tmp54 ;
goto __ats_lab_aux_36 ; // tail call
} else {
tmp52 = ats_true_bool ;
} /* end of [if] */
} /* end of [if] */
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_1_1:
tmp52 = ats_false_bool ;
break ;
} while (0) ;
return (tmp52) ;
} /* end of [aux_36] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
ats_clo_ref_type closure_env_1 ;
} aux_36_closure_type ;

ats_bool_type
aux_36_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return aux_36 (((aux_36_closure_type*)cloptr)->closure_env_0, ((aux_36_closure_type*)cloptr)->closure_env_1, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
aux_36_closure_init (aux_36_closure_type *p_clo, ats_int_type env0, ats_clo_ref_type env1) {
p_clo->closure_fun = (ats_fun_ptr_type)&aux_36_clofun ;
p_clo->closure_env_0 = env0 ;
p_clo->closure_env_1 = env1 ;
return ;
} /* end of function */

ats_clo_ptr_type
aux_36_closure_make (ats_int_type env0, ats_clo_ref_type env1) {
aux_36_closure_type *p_clo = ATS_MALLOC(sizeof(aux_36_closure_type)) ;
aux_36_closure_init (p_clo, env0, env1) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/Research/ATS-Anairiats/libats/DATS/funset_listord.dats: 3645(line=137, offs=3) -- 3986(line=148, offs=4)
*/
ATSstaticdec()
ats_bool_type
funset_is_member_02272_ats_int_type (ats_ptr_type arg0, ats_int_type arg1, ats_clo_ref_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp51) ;

__ats_lab_funset_is_member_02272_ats_int_type:
tmp51 = aux_36 (arg1, arg2, arg0) ;
return (tmp51) ;
} /* end of [funset_is_member_02272_ats_int_type] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_solve.dats: 8386(line=373, offs=3) -- 8429(line=373, offs=46)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__indexset_is_member (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp50) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__indexset_is_member:
tmp50 = funset_is_member_02272_ats_int_type (arg0, arg1, cmp_31_closure_make ()) ;
return (tmp50) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__indexset_is_member] */

/*
// /home/hwxi/Research/ATS-Anairiats/libats/DATS/funset_listord.dats: 4180(line=158, offs=7) -- 4779(line=176, offs=10)
*/
ATSstaticdec()
ats_ptr_type
ins_40 (ats_int_type env0, ats_clo_ref_type env1, ats_ptr_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_int_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_int_type, tmp66) ;
ATSlocal (ats_bool_type, tmp67) ;
ATSlocal (ats_int_type, tmp68) ;
ATSlocal (ats_bool_type, tmp69) ;
ATSlocal (ats_int_type, tmp70) ;
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (ats_bool_type, tmp72) ;
ATSlocal (ats_int_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;

__ats_lab_ins_40:
do {
/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp64 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp65 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
tmp66 = compare_elt_elt_02267_ats_int_type (env0, tmp64, env1) ;
tmp67 = atspre_gt_int_int (tmp66, 0) ;
if (tmp67) {
tmp68 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg1), 1) ;
ats_ptrget_mac(ats_int_type, arg1) = tmp68 ;
tmp63 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp63, atslab_0, env0) ;
ats_selptrset_mac(anairiats_sum_1, tmp63, atslab_1, arg0) ;
} else {
tmp69 = atspre_lt_int_int (tmp66, 0) ;
if (tmp69) {
tmp70 = ats_ptrget_mac(ats_int_type, arg1) ;
tmp71 = ins_40 (env0, env1, tmp65, arg1) ;
tmp72 = atspre_eq_int_int (ats_ptrget_mac(ats_int_type, arg1), tmp70) ;
if (tmp72) {
tmp63 = arg0 ;
} else {
tmp63 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp63, atslab_0, tmp64) ;
ats_selptrset_mac(anairiats_sum_1, tmp63, atslab_1, tmp71) ;
} /* end of [if] */
} else {
tmp63 = arg0 ;
} /* end of [if] */
} /* end of [if] */
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_3_1:
tmp73 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg1), 1) ;
ats_ptrget_mac(ats_int_type, arg1) = tmp73 ;
tmp74 = (ats_sum_ptr_type)0 ;
tmp63 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp63, atslab_0, env0) ;
ats_selptrset_mac(anairiats_sum_1, tmp63, atslab_1, tmp74) ;
break ;
} while (0) ;
return (tmp63) ;
} /* end of [ins_40] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
ats_clo_ref_type closure_env_1 ;
} ins_40_closure_type ;

ats_ptr_type
ins_40_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0, ats_ref_type arg1) {
return ins_40 (((ins_40_closure_type*)cloptr)->closure_env_0, ((ins_40_closure_type*)cloptr)->closure_env_1, arg0, arg1) ;
} /* end of function */

ATSinline()
ats_void_type
ins_40_closure_init (ins_40_closure_type *p_clo, ats_int_type env0, ats_clo_ref_type env1) {
p_clo->closure_fun = (ats_fun_ptr_type)&ins_40_clofun ;
p_clo->closure_env_0 = env0 ;
p_clo->closure_env_1 = env1 ;
return ;
} /* end of function */

ats_clo_ptr_type
ins_40_closure_make (ats_int_type env0, ats_clo_ref_type env1) {
ins_40_closure_type *p_clo = ATS_MALLOC(sizeof(ins_40_closure_type)) ;
ins_40_closure_init (p_clo, env0, env1) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/Research/ATS-Anairiats/libats/DATS/funset_listord.dats: 4154(line=157, offs=3) -- 4907(line=182, offs=4)
*/
ATSstaticdec()
ats_bool_type
funset_insert_02274_ats_int_type (ats_ref_type arg0, ats_int_type arg1, ats_clo_ref_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp62) ;
ATSlocal (ats_int_type, tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_bool_type, tmp77) ;

__ats_lab_funset_insert_02274_ats_int_type:
/* ats_int_type tmp75 ; */
tmp75 = 0 ;
tmp76 = ins_40 (arg1, arg2, ats_ptrget_mac(ats_ptr_type, arg0), (&tmp75)) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp76 ;
tmp77 = atspre_eq_int_int (tmp75, 0) ;
if (tmp77) {
tmp62 = ats_true_bool ;
} else {
tmp62 = ats_false_bool ;
} /* end of [if] */
return (tmp62) ;
} /* end of [funset_insert_02274_ats_int_type] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_solve.dats: 8487(line=378, offs=3) -- 8573(line=382, offs=2)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__indexset_add (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
ATSlocal (ats_bool_type, tmp61) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__indexset_add:
/* ats_ptr_type tmp60 ; */
tmp60 = arg0 ;
tmp61 = funset_insert_02274_ats_int_type ((&tmp60), arg1, cmp_31_closure_make ()) ;
tmp59 = tmp60 ;
return (tmp59) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__indexset_add] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 6702(line=253, offs=5) -- 6923(line=259, offs=4)
*/
ATSstaticdec()
ats_void_type
loop_44 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp88) ;
ATSlocal (ats_ptr_type, tmp89) ;

__ats_lab_loop_44:
do {
/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (ats_ptrget_mac(ats_ptr_type, arg0) == (ats_sum_ptr_type)0) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp89 = &ats_caselptrlab_mac(anairiats_sum_1, ats_ptrget_mac(ats_ptr_type, arg0), atslab_1) ;
arg0 = tmp89 ;
arg1 = arg1 ;
goto __ats_lab_loop_44 ; // tail call
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
// if (ats_ptrget_mac(ats_ptr_type, arg0) != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_5_1:
ats_ptrget_mac(ats_ptr_type, arg0) = arg1 ;
break ;
} while (0) ;
return /* (tmp88) */ ;
} /* end of [loop_44] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 6567(line=247, offs=16) -- 6970(line=262, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_vt_append_01504_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
// ATSlocal_void (tmp90) ;

__ats_lab_list_vt_append_01504_ats_int_type:
/* ats_ptr_type tmp87 ; */
tmp87 = arg0 ;
/* tmp90 = */ loop_44 ((&tmp87), arg1) ;
tmp86 = tmp87 ;
return (tmp86) ;
} /* end of [list_vt_append_01504_ats_int_type] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_solve.dats: 8714(line=393, offs=1) -- 9047(line=413, offs=2)
*/
ATSstaticdec()
ats_ptr_type
loop_42 (ats_ptr_type env0, ats_int_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_bool_type, tmp80) ;
ATSlocal (ats_bool_type, tmp81) ;
ATSlocal (ats_int_type, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_int_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;

__ats_lab_loop_42:
tmp80 = atspre_igt (arg0, 0) ;
if (tmp80) {
tmp81 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__indexset_is_member (env0, arg0) ;
if (tmp81) {
tmp82 = atspre_isub (arg0, 1) ;
tmp83 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp83, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_1, tmp83, atslab_1, arg1) ;
arg0 = tmp82 ;
arg1 = tmp83 ;
arg2 = arg2 ;
goto __ats_lab_loop_42 ; // tail call
} else {
tmp84 = atspre_isub (arg0, 1) ;
tmp85 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp85, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_1, tmp85, atslab_1, arg2) ;
arg0 = tmp84 ;
arg1 = arg1 ;
arg2 = tmp85 ;
goto __ats_lab_loop_42 ; // tail call
} /* end of [if] */
} else {
tmp79 = list_vt_append_01504_ats_int_type (arg1, arg2) ;
} /* end of [if] */
return (tmp79) ;
} /* end of [loop_42] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} loop_42_closure_type ;

ats_ptr_type
loop_42_clofun (ats_clo_ptr_type cloptr, ats_int_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
return loop_42 (((loop_42_closure_type*)cloptr)->closure_env_0, arg0, arg1, arg2) ;
} /* end of function */

ATSinline()
ats_void_type
loop_42_closure_init (loop_42_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&loop_42_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
loop_42_closure_make (ats_ptr_type env0) {
loop_42_closure_type *p_clo = ATS_MALLOC(sizeof(loop_42_closure_type)) ;
loop_42_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_solve.dats: 8653(line=388, offs=6) -- 9112(line=416, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_make (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_int_type, tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_make:
tmp91 = atspre_isub (arg1, 1) ;
tmp92 = (ats_sum_ptr_type)0 ;
tmp93 = (ats_sum_ptr_type)0 ;
tmp78 = loop_42 (arg0, tmp91, tmp92, tmp93) ;
return (tmp78) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_make] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 4893(line=177, offs=7) -- 5015(line=178, offs=73)
*/
ATSstaticdec()
ats_void_type
loop_47 (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;

__ats_lab_loop_47:
do {
/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp97 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
ATS_FREE(arg0) ;
arg0 = tmp97 ;
goto __ats_lab_loop_47 ; // tail call
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_7_1:
break ;
} while (0) ;
return /* (tmp96) */ ;
} /* end of [loop_47] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 4875(line=176, offs=14) -- 5054(line=182, offs=4)
*/
ATSstaticdec()
ats_void_type
list_vt_free_01499_ats_int_type (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp95) ;

__ats_lab_list_vt_free_01499_ats_int_type:
/* tmp95 = */ loop_47 (arg0) ;
return /* (tmp95) */ ;
} /* end of [list_vt_free_01499_ats_int_type] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_solve.dats: 9163(line=419, offs=14) -- 9185(line=419, offs=36)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_free (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp94) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_free:
/* tmp94 = */ list_vt_free_01499_ats_int_type (arg0) ;
return /* (tmp94) */ ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_free] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_lintprgm_solve.dats: 9213(line=422, offs=16) -- 9323(line=427, offs=37)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_choose (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp98) ;
ATSlocal (ats_int_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_choose:
do {
/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (ats_ptrget_mac(ats_ptr_type, arg0) == (ats_sum_ptr_type)0) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp99 = ats_caselptrlab_mac(anairiats_sum_1, ats_ptrget_mac(ats_ptr_type, arg0), atslab_0) ;
tmp100 = ats_caselptrlab_mac(anairiats_sum_1, ats_ptrget_mac(ats_ptr_type, arg0), atslab_1) ;
ATS_FREE(ats_ptrget_mac(ats_ptr_type, arg0)) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp100 ;
tmp98 = tmp99 ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
// if (ats_ptrget_mac(ats_ptr_type, arg0) != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_9_1:
tmp98 = 0 ;
break ;
} while (0) ;
return (tmp98) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__indexlst_choose] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_atspre_2edats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2unsafe_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_print_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_intinf_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e12_2libats_2SATS_2funset_listord_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e12_2libats_2DATS_2funset_listord_2edats__staload (void) ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__staload () {
static int _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__staload_flag) return ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__staload_flag = 1 ;

// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_atspre_2edats__staload () ;
// ATS_2d0_2e2_2e12_2prelude_2SATS_2unsafe_2esats__staload () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2unsafe_2edats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2edats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_print_2edats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_intinf_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__staload () ;
ATS_2d0_2e2_2e12_2libats_2SATS_2funset_listord_2esats__staload () ;
ATS_2d0_2e2_2e12_2libats_2DATS_2funset_listord_2edats__staload () ;

_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVLSTnil_0.tag = 0 ;
// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVLSTcons_1.tag = 1 ;
// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVLSTmark_2.tag = 2 ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVEQLSTnil_0.tag = 0 ;
// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVEQLSTcons_1.tag = 1 ;
// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__MYIVEQLSTmark_2.tag = 2 ;
return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__dynload () {
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__dynload_flag = 1 ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_solve_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__myintvecout_addback_prfck () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lintprgm_2esats__myintvecout0_addback_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_lintprgm_solve_dats.c] */
