/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2017-11-12:  9h:13m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_tokbuf.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_tokbuf.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef
struct {
ats_ptr_type atslab_token_loc ;
ats_ptr_type atslab_token_node ;
} anairiats_rec_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_2 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_3 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__None_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__Some_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_AT_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_BANG_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_BACKSLASH_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_COLON_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_COLONLT_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_EQ_13) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_LT_21) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_GT_22) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_GTLT_23) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_MINUSGT_27) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_MINUSLTGT_29) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_TILDE_30) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_FUN_52) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_VAL_80) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_IDENT_alp_143) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_IDENT_sym_144) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_IDENT_dlr_147) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_IDENT_ext_149) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_INT_150) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_STRING_154) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__T_LPAREN_157) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_i0nt_38) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_s0tring_41) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_i0de_42) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_i0dext_43) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_i0de_dlr_44) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_l0ab_56) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_p0rec_57) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_colonwith_59) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null) () ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_is_null) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__e0fftag_i0de) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__e0fftag_i0nt) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__e0fftag_cst) (ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__e0fftag_var_fun) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__p0rec_emp) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__p0rec_i0de) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__p0rec_i0de_adj) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__p0rec_i0nt) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__l0ab_make_i0de) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__l0ab_make_i0nt) (ats_ptr_type) ;
ATSextern_fun(ats_uint_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_ntok) (ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_set_ntok) (ats_ref_type, ats_uint_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1) (ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token) (ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__the_parerrlst_add_ifnbt) (ats_int_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__tokbuf_set_ntok_null) (ats_ref_type, ats_uint_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_RPAREN) (ats_ref_type, ats_int_type, ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_GT) (ats_ref_type, ats_int_type, ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__pstar_fun0_COMMA) (ats_ref_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__pstar1_fun) (ats_ref_type, ats_int_type, ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__ptest_fun) (ats_ref_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__pif_fun) (ats_ref_type, ats_int_type, ats_ref_type, ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__ptokwrap_fun) (ats_ref_type, ats_int_type, ats_ref_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0nt) (ats_ref_type, ats_int_type, ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_s0tring) (ats_ref_type, ats_int_type, ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0de) (ats_ref_type, ats_int_type, ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_e0fftag) (ats_ref_type, ats_int_type, ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_e0fftaglst) (ats_ref_type, ats_int_type, ats_ref_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type p_p0rec_tok_7 (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2, ats_ptr_type arg3) ;
static
ats_ptr_type p_effi0de_9 (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 1859(line=66, offs=8) -- 2222(line=84, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0nt (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
// ATSlocal_void (tmp4) ;
ATSlocal (ats_int_type, tmp5) ;
// ATSlocal_void (tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0nt:
tmp1 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
tmp2 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp1), atslab_token_loc) ;
tmp3 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp1), atslab_token_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp3)->tag != 150) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
/* tmp4 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp0 = tmp1 ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
__ats_lab_1_1:
tmp5 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg2), 1) ;
ats_ptrget_mac(ats_int_type, arg2) = tmp5 ;
tmp7 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_i0nt_38) ;
/* tmp6 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__the_parerrlst_add_ifnbt (arg1, tmp2, tmp7) ;
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
break ;
} while (0) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0nt] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 2286(line=90, offs=3) -- 2658(line=108, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_s0tring (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;
// ATSlocal_void (tmp12) ;
ATSlocal (ats_int_type, tmp13) ;
// ATSlocal_void (tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_s0tring:
tmp9 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
tmp10 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp9), atslab_token_loc) ;
tmp11 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp9), atslab_token_node) ;
do {
/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)tmp11)->tag != 154) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
/* tmp12 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp8 = tmp9 ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
__ats_lab_3_1:
tmp13 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg2), 1) ;
ats_ptrget_mac(ats_int_type, arg2) = tmp13 ;
tmp15 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_s0tring_41) ;
/* tmp14 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__the_parerrlst_add_ifnbt (arg1, tmp10, tmp15) ;
tmp8 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
break ;
} while (0) ;
return (tmp8) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_s0tring] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 2886(line=130, offs=8) -- 4169(line=187, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0de (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
// ATSlocal_void (tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
// ATSlocal_void (tmp23) ;
// ATSlocal_void (tmp24) ;
// ATSlocal_void (tmp25) ;
// ATSlocal_void (tmp26) ;
// ATSlocal_void (tmp27) ;
// ATSlocal_void (tmp28) ;
// ATSlocal_void (tmp29) ;
// ATSlocal_void (tmp30) ;
// ATSlocal_void (tmp31) ;
// ATSlocal_void (tmp32) ;
// ATSlocal_void (tmp33) ;
ATSlocal (ats_int_type, tmp34) ;
// ATSlocal_void (tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0de:
tmp17 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
tmp18 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp17), atslab_token_loc) ;
tmp19 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp17), atslab_token_node) ;
do {
/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)tmp19)->tag != 143) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp20 = ats_caselptrlab_mac(anairiats_sum_2, tmp19, atslab_0) ;
/* tmp21 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, tmp20) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)tmp19)->tag != 144) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp22 = ats_caselptrlab_mac(anairiats_sum_2, tmp19, atslab_0) ;
/* tmp23 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, tmp22) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)tmp19)->tag != 13) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
/* tmp24 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, ATSstrcst("=")) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)tmp19)->tag != 22) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
/* tmp25 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, ATSstrcst(">")) ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)tmp19)->tag != 21) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
/* tmp26 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, ATSstrcst("<")) ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp19)->tag != 1) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
/* tmp27 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, ATSstrcst("@")) ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (((ats_sum_ptr_type)tmp19)->tag != 5) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
/* tmp28 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, ATSstrcst("\\")) ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (((ats_sum_ptr_type)tmp19)->tag != 3) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
/* tmp29 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, ATSstrcst("!")) ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (((ats_sum_ptr_type)tmp19)->tag != 30) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
/* tmp30 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, ATSstrcst("~")) ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (((ats_sum_ptr_type)tmp19)->tag != 27) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
/* tmp31 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, ATSstrcst("->")) ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)tmp19)->tag != 29) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
/* tmp32 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, ATSstrcst("-<>")) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (((ats_sum_ptr_type)tmp19)->tag != 23) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
/* tmp33 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp18, ATSstrcst("><")) ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
__ats_lab_16_1:
tmp34 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg2), 1) ;
ats_ptrget_mac(ats_int_type, arg2) = tmp34 ;
tmp36 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_i0de_42) ;
/* tmp35 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__the_parerrlst_add_ifnbt (arg1, tmp18, tmp36) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
break ;
} while (0) ;
return (tmp16) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0de] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 4260(line=196, offs=3) -- 4355(line=200, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0deseq1 (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0deseq1:
tmp38 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__pstar1_fun (arg0, arg1, arg2, &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0de) ;
tmp37 = ats_castfn_mac(ats_ptr_type, tmp38) ;
return (tmp37) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0deseq1] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 4422(line=206, offs=3) -- 4824(line=224, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0dext (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
// ATSlocal_void (tmp44) ;
ATSlocal (ats_int_type, tmp45) ;
// ATSlocal_void (tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0dext:
tmp40 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
tmp41 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp40), atslab_token_loc) ;
tmp42 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp40), atslab_token_node) ;
do {
/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (((ats_sum_ptr_type)tmp42)->tag != 149) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp43 = ats_caselptrlab_mac(anairiats_sum_2, tmp42, atslab_0) ;
/* tmp44 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp39 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp41, tmp43) ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
__ats_lab_18_1:
tmp45 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg2), 1) ;
ats_ptrget_mac(ats_int_type, arg2) = tmp45 ;
tmp47 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_i0dext_43) ;
/* tmp46 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__the_parerrlst_add_ifnbt (arg1, tmp41, tmp47) ;
tmp39 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
break ;
} while (0) ;
return (tmp39) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0dext] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 4891(line=230, offs=3) -- 5295(line=248, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0de_dlr (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;
// ATSlocal_void (tmp53) ;
ATSlocal (ats_int_type, tmp54) ;
// ATSlocal_void (tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0de_dlr:
tmp49 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
tmp50 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp49), atslab_token_loc) ;
tmp51 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp49), atslab_token_node) ;
do {
/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (((ats_sum_ptr_type)tmp51)->tag != 147) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
tmp52 = ats_caselptrlab_mac(anairiats_sum_2, tmp51, atslab_0) ;
/* tmp53 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp48 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp50, tmp52) ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
__ats_lab_20_1:
tmp54 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg2), 1) ;
ats_ptrget_mac(ats_int_type, arg2) = tmp54 ;
tmp56 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_i0de_dlr_44) ;
/* tmp55 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__the_parerrlst_add_ifnbt (arg1, tmp50, tmp56) ;
tmp48 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
break ;
} while (0) ;
return (tmp48) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0de_dlr] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 5452(line=262, offs=3) -- 5947(line=286, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_l0ab (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp57) ;
ATSlocal (ats_ptr_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_bool_type, tmp62) ;
// ATSlocal_void (tmp63) ;
ATSlocal (ats_int_type, tmp64) ;
// ATSlocal_void (tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_l0ab:
/* ats_ptr_type tmp58 ; */
tmp59 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
tmp60 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp59), atslab_token_loc) ;
tmp61 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp59), atslab_token_node) ;
do {
/* branch: __ats_lab_21 */
__ats_lab_21_0:
__ats_lab_21_1:
tmp62 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__ptest_fun (arg0, &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0de, (&tmp58)) ;
if (!tmp62) { goto __ats_lab_22_0 ; }
tmp57 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__l0ab_make_i0de (ats_castfn_mac(ats_ptr_type, tmp58)) ;
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
if (((ats_sum_ptr_type)tmp61)->tag != 150) { goto __ats_lab_23_0 ; }
__ats_lab_22_1:
/* tmp63 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp57 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__l0ab_make_i0nt (tmp59) ;
break ;

/* branch: __ats_lab_23 */
__ats_lab_23_0:
__ats_lab_23_1:
tmp64 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg2), 1) ;
ats_ptrget_mac(ats_int_type, arg2) = tmp64 ;
tmp66 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_l0ab_56) ;
/* tmp65 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__the_parerrlst_add_ifnbt (arg1, tmp60, tmp66) ;
tmp57 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
break ;
} while (0) ;
return (tmp57) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_l0ab] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 6124(line=299, offs=1) -- 7214(line=345, offs=4)
*/
ATSstaticdec()
ats_ptr_type
p_p0rec_tok_7 (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_int_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;
// ATSlocal_void (tmp71) ;
// ATSlocal_void (tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_bool_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_bool_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_ptr_type, tmp80) ;
ATSlocal (ats_bool_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;
ATSlocal (ats_bool_type, tmp83) ;

__ats_lab_p_p0rec_tok_7:
/* ats_ptr_type tmp68 ; */
tmp69 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp70 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg3), atslab_token_node) ;
do {
/* branch: __ats_lab_24 */
__ats_lab_24_0:
if (((ats_sum_ptr_type)tmp70)->tag != 150) { goto __ats_lab_25_0 ; }
__ats_lab_24_1:
/* tmp71 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp67 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__p0rec_i0nt (arg3) ;
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (((ats_sum_ptr_type)tmp70)->tag != 157) { goto __ats_lab_28_0 ; }
__ats_lab_25_1:
/* tmp72 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp73 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0de (arg0, 0, arg2) ;
tmp74 = atspre_eq_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp69) ;
if (tmp74) {
tmp75 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
tmp76 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp75), atslab_token_node) ;
do {
/* branch: __ats_lab_26 */
__ats_lab_26_0:
__ats_lab_26_1:
tmp77 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__ptest_fun (arg0, &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0de, (&tmp68)) ;
if (!tmp77) { goto __ats_lab_27_1 ; }
tmp78 = ats_castfn_mac(ats_ptr_type, tmp68) ;
tmp79 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_i0nt (arg0, 0, arg2) ;
tmp80 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__pif_fun (arg0, 0, arg2, &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_RPAREN, tmp69) ;
tmp81 = atspre_eq_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp69) ;
if (tmp81) {
tmp67 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__p0rec_i0de_adj (tmp73, tmp78, tmp79) ;
} else {
tmp67 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
} /* end of [if] */
break ;

/* branch: __ats_lab_27 */
__ats_lab_27_0:
__ats_lab_27_1:
tmp82 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_RPAREN (arg0, 0, arg2) ;
tmp83 = atspre_eq_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp69) ;
if (tmp83) {
tmp67 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__p0rec_i0de (tmp73) ;
} else {
tmp67 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
} /* end of [if] */
break ;
} while (0) ;
} else {
tmp67 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
} /* end of [if] */
break ;

/* branch: __ats_lab_28 */
__ats_lab_28_0:
__ats_lab_28_1:
tmp67 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__p0rec_emp () ;
break ;
} while (0) ;
return (tmp67) ;
} /* end of [p_p0rec_tok_7] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 7260(line=349, offs=3) -- 7329(line=350, offs=53)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_p0rec (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_p0rec:
tmp85 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_p0rec_57) ;
tmp84 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__ptokwrap_fun (arg0, arg1, arg2, &p_p0rec_tok_7, tmp85) ;
return (tmp84) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_p0rec] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 7376(line=356, offs=1) -- 7744(line=373, offs=4)
*/
ATSstaticdec()
ats_ptr_type
p_effi0de_9 (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (ats_ptr_type, tmp90) ;
// ATSlocal_void (tmp91) ;
ATSlocal (ats_int_type, tmp92) ;

__ats_lab_p_effi0de_9:
tmp87 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
tmp88 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp87), atslab_token_loc) ;
tmp89 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp87), atslab_token_node) ;
do {
/* branch: __ats_lab_29 */
__ats_lab_29_0:
if (((ats_sum_ptr_type)tmp89)->tag != 143) { goto __ats_lab_30_0 ; }
__ats_lab_29_1:
tmp90 = ats_caselptrlab_mac(anairiats_sum_2, tmp89, atslab_0) ;
/* tmp91 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp86 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__i0de_make_string (tmp88, tmp90) ;
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
__ats_lab_30_1:
tmp92 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg2), 1) ;
ats_ptrget_mac(ats_int_type, arg2) = tmp92 ;
tmp86 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
break ;
} while (0) ;
return (tmp86) ;
} /* end of [p_effi0de_9] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 7879(line=385, offs=3) -- 8843(line=432, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_e0fftag (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_int_type, tmp94) ;
ATSlocal (ats_uint_type, tmp95) ;
ATSlocal (ats_ptr_type, tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;
ATSlocal (ats_ptr_type, tmp98) ;
// ATSlocal_void (tmp99) ;
// ATSlocal_void (tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;
ATSlocal (ats_bool_type, tmp102) ;
// ATSlocal_void (tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;
ATSlocal (ats_bool_type, tmp105) ;
// ATSlocal_void (tmp106) ;
ATSlocal (ats_bool_type, tmp107) ;
ATSlocal (ats_int_type, tmp108) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_e0fftag:
tmp94 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp95 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_ntok (arg0) ;
tmp96 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
/* ats_ptr_type tmp97 ; */
tmp98 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp96), atslab_token_node) ;
do {
/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (((ats_sum_ptr_type)tmp98)->tag != 52) { goto __ats_lab_32_0 ; }
__ats_lab_31_1:
/* tmp99 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp93 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__e0fftag_var_fun (tmp96) ;
break ;

/* branch: __ats_lab_32 */
__ats_lab_32_0:
if (((ats_sum_ptr_type)tmp98)->tag != 3) { goto __ats_lab_33_0 ; }
__ats_lab_32_1:
/* tmp100 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp101 = p_effi0de_9 (arg0, 0, arg2) ;
tmp102 = atspre_eq_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp94) ;
if (tmp102) {
tmp93 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__e0fftag_cst (0, tmp101) ;
} else {
tmp93 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__tokbuf_set_ntok_null (arg0, tmp95) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_33 */
__ats_lab_33_0:
if (((ats_sum_ptr_type)tmp98)->tag != 30) { goto __ats_lab_34_0 ; }
__ats_lab_33_1:
/* tmp103 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp104 = p_effi0de_9 (arg0, 0, arg2) ;
tmp105 = atspre_eq_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp94) ;
if (tmp105) {
tmp93 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__e0fftag_cst (0, tmp104) ;
} else {
tmp93 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__tokbuf_set_ntok_null (arg0, tmp95) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_34 */
__ats_lab_34_0:
if (((ats_sum_ptr_type)tmp98)->tag != 150) { goto __ats_lab_35_0 ; }
__ats_lab_34_1:
/* tmp106 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp93 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__e0fftag_i0nt (tmp96) ;
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
__ats_lab_35_1:
tmp107 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__ptest_fun (arg0, &p_effi0de_9, (&tmp97)) ;
if (!tmp107) { goto __ats_lab_36_1 ; }
tmp93 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__e0fftag_i0de (ats_castfn_mac(ats_ptr_type, tmp97)) ;
break ;

/* branch: __ats_lab_36 */
__ats_lab_36_0:
__ats_lab_36_1:
tmp108 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg2), 1) ;
ats_ptrget_mac(ats_int_type, arg2) = tmp108 ;
tmp93 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
break ;
} while (0) ;
return (tmp93) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_e0fftag] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 8892(line=436, offs=3) -- 8964(line=437, offs=50)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_e0fftaglst (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_e0fftaglst:
tmp110 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__pstar_fun0_COMMA (arg0, arg1, &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_e0fftag) ;
tmp109 = ats_castfn_mac(ats_ptr_type, tmp110) ;
return (tmp109) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_e0fftaglst] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 9104(line=450, offs=3) -- 9908(line=486, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_colonwith (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp111) ;
ATSlocal (ats_int_type, tmp112) ;
ATSlocal (ats_uint_type, tmp113) ;
ATSlocal (ats_ptr_type, tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;
ATSlocal (ats_ptr_type, tmp116) ;
// ATSlocal_void (tmp117) ;
// ATSlocal_void (tmp118) ;
ATSlocal (ats_ptr_type, tmp119) ;
ATSlocal (ats_ptr_type, tmp120) ;
ATSlocal (ats_bool_type, tmp121) ;
ATSlocal (ats_int_type, tmp122) ;
// ATSlocal_void (tmp123) ;
ATSlocal (ats_ptr_type, tmp124) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_colonwith:
tmp112 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp113 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_ntok (arg0) ;
tmp114 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
tmp115 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp114), atslab_token_loc) ;
tmp116 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp114), atslab_token_node) ;
do {
/* branch: __ats_lab_37 */
__ats_lab_37_0:
if (((ats_sum_ptr_type)tmp116)->tag != 6) { goto __ats_lab_38_0 ; }
__ats_lab_37_1:
/* tmp117 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp111 = (ats_sum_ptr_type)0 ;
break ;

/* branch: __ats_lab_38 */
__ats_lab_38_0:
if (((ats_sum_ptr_type)tmp116)->tag != 7) { goto __ats_lab_39_0 ; }
__ats_lab_38_1:
/* tmp118 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp119 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_e0fftaglst (arg0, 0, arg2) ;
tmp120 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_GT (arg0, 0, arg2) ;
tmp121 = atspre_eq_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp112) ;
if (tmp121) {
tmp111 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
ats_selptrset_mac(anairiats_sum_3, tmp111, atslab_0, tmp119) ;
} else {
tmp111 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__tokbuf_set_ntok_null (arg0, tmp113) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_39 */
__ats_lab_39_0:
__ats_lab_39_1:
tmp122 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg2), 1) ;
ats_ptrget_mac(ats_int_type, arg2) = tmp122 ;
tmp124 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__PE_colonwith_59) ;
/* tmp123 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__the_parerrlst_add_ifnbt (arg1, tmp115, tmp124) ;
tmp111 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
break ;
} while (0) ;
return (tmp111) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_colonwith] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 9978(line=492, offs=3) -- 10298(line=509, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_dcstkind (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp125) ;
ATSlocal (ats_ptr_type, tmp126) ;
ATSlocal (ats_ptr_type, tmp127) ;
// ATSlocal_void (tmp128) ;
// ATSlocal_void (tmp129) ;
ATSlocal (ats_int_type, tmp130) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_dcstkind:
tmp126 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
tmp127 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp126), atslab_token_node) ;
do {
/* branch: __ats_lab_40 */
__ats_lab_40_0:
if (((ats_sum_ptr_type)tmp127)->tag != 52) { goto __ats_lab_41_0 ; }
__ats_lab_40_1:
/* tmp128 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp125 = tmp126 ;
break ;

/* branch: __ats_lab_41 */
__ats_lab_41_0:
if (((ats_sum_ptr_type)tmp127)->tag != 80) { goto __ats_lab_42_0 ; }
__ats_lab_41_1:
/* tmp129 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp125 = tmp126 ;
break ;

/* branch: __ats_lab_42 */
__ats_lab_42_0:
__ats_lab_42_1:
tmp130 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg2), 1) ;
ats_ptrget_mac(ats_int_type, arg2) = tmp130 ;
tmp125 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_null () ;
break ;
} while (0) ;
return (tmp125) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_dcstkind] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_parsing_base.dats: 10420(line=519, offs=3) -- 10817(line=537, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_extnamopt (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp131) ;
ATSlocal (ats_uint_type, tmp132) ;
ATSlocal (ats_ptr_type, tmp133) ;
ATSlocal (ats_ptr_type, tmp134) ;
// ATSlocal_void (tmp135) ;
ATSlocal (ats_ptr_type, tmp136) ;
ATSlocal (ats_bool_type, tmp137) ;
// ATSlocal_void (tmp138) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_extnamopt:
tmp132 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_ntok (arg0) ;
tmp133 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_get_token (arg0) ;
tmp134 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp133), atslab_token_node) ;
do {
/* branch: __ats_lab_43 */
__ats_lab_43_0:
if (((ats_sum_ptr_type)tmp134)->tag != 13) { goto __ats_lab_44_0 ; }
__ats_lab_43_1:
/* tmp135 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_incby1 (arg0) ;
tmp136 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_s0tring (arg0, 0, arg2) ;
tmp137 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__synent_is_null (tmp136) ;
if (tmp137) {
/* tmp138 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__tokbuf_set_ntok (arg0, tmp132) ;
tmp131 = (ats_sum_ptr_type)0 ;
} else {
tmp131 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
ats_selptrset_mac(anairiats_sum_3, tmp131, atslab_0, tmp136) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_44 */
__ats_lab_44_0:
__ats_lab_44_1:
tmp131 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp131) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__p_extnamopt] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_atspre_2edats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_symbol_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_label_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_base_2edats__staload () {
static int _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_base_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_base_2edats__staload_flag) return ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_base_2edats__staload_flag = 1 ;

// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_atspre_2edats__staload () ;
// ATS_2d0_2e2_2e12_2prelude_2SATS_2unsafe_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_symbol_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_label_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_syntax_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_lexing_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_tokbuf_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_base_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_base_2edats__dynload () {
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_base_2edats__dynload_flag = 1 ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_base_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_parsing_base_dats.c] */
