---
- functions:
  - {name: unsafePerformIO, within: []}
  - {name: undefined, within: []}

- ignore: {name: Avoid lambda, within: [Language.ATS.Types.Lens]}
- ignore: {name: Use <$>, within: [Language.ATS.PrettyPrint]}
- ignore: {name: Unused LANGUAGE pragma, within: [Language.ATS.PrettyPrint]}
- ignore: {name: Functor law, within: [Language.ATS.PrettyPrint]}
- ignore: {name: Evaluate, within: [Language.ATS.Generate]}

- fixity: infixr 8 .*
- fixity: infixr 3 ***
- fixity: infixr 3 &&&
- fixity: infixr 1 <=<
