---
- ignore: {name: Avoid lambda, within: [Language.ATS.Types.Lens]}
- ignore: {name: Unused LANGUAGE pragma, within: [Language.ATS.PrettyPrint]}
- ignore: {name: Use foldr, within: [Language.ATS.Generate]}
- ignore: {name: Use section}

- fixity: infixr 8 .*
- fixity: infixr 3 ***
- fixity: infixr 3 &&&
- fixity: infixr 1 <=<
